/*
 * Sample API
 *
 * Device manager for Tasmota devices via MQTT [Source](https://github.com/mbezuidenhout/tdm).
 *
 * API version: 0.1.0
 * Contact: marius.bezuidenhout@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gorilla/mux"
	"golang.org/x/exp/slices"
)

func DevicesPost(w http.ResponseWriter, r *http.Request) {
	apiKey := r.Header.Get("X-Api-Key")
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if managers[apiKey] == nil {
		w.WriteHeader(http.StatusUnauthorized)
	} else {
		managers[apiKey].lastUpdate = time.Now()
		w.WriteHeader(http.StatusOK)
		data, _ := json.Marshal(managers[apiKey].GetDevices())
		fmt.Fprintln(w, string(data))
	}
}

func DeviceDeviceTopicGet(w http.ResponseWriter, r *http.Request) {
	apiKey := r.Header.Get("X-Api-Key")
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if managers[apiKey] == nil {
		w.WriteHeader(http.StatusUnauthorized)
	} else {
		deviceTopic, ok := mux.Vars(r)["deviceTopic"]
		if !ok {
			w.WriteHeader(http.StatusUnprocessableEntity)
		} else {
			managers[apiKey].lastUpdate = time.Now()
			w.WriteHeader(http.StatusOK)
			data, _ := json.Marshal(managers[apiKey].GetDevice(deviceTopic))
			fmt.Fprintln(w, string(data))
			fmt.Printf("Context %s", deviceTopic)
		}
	}
}

func DeviceDeviceTopicPost(w http.ResponseWriter, r *http.Request) {
	cmndWhiteList := []string{"devicename", "zbname", "zbinfo", "zbpermitjoin", "zbsend"}
	apiKey := r.Header.Get("X-Api-Key")
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	if managers[apiKey] == nil {
		w.WriteHeader(http.StatusUnauthorized)
	} else {
		deviceTopic, ok1 := mux.Vars(r)["deviceTopic"]
		command := r.URL.Query().Get("command")
		payload := r.URL.Query().Get("payload")

		if !ok1 {
			w.WriteHeader(http.StatusUnprocessableEntity)
		} else {
			managers[apiKey].lastUpdate = time.Now()
			device := managers[apiKey].GetDevice(deviceTopic)
			if slices.Contains(cmndWhiteList, strings.ToLower(command)) {
				device.SendCmnd(command, payload)
				w.WriteHeader(http.StatusOK)
				fmt.Printf("Context: %s, Command: %s, Payload: %s", deviceTopic, command, payload)
			} else {
				w.WriteHeader(http.StatusBadRequest)
			}
		}
	}
}
